name: Docker Image CI Dev Mode

concurrency:
  group: "build"
  cancel-in-progress: false

on:
  pull_request:
    branches: [ "master" ]

jobs:

  Build-and-Push:

    runs-on: dal-1

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push image for the web server on dev mode
      uses: docker/build-push-action@v5
      with:
          context: .
          file: web-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cblwebserver-dev:latest
    - name: Build and push image for the ban importer on dev mode
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ban-importer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cblimporter-dev:latest
